### ISSUE TITLE
error on short audio

### ISSUE THREAD

**Issue by georgid** [sertansenturk/predominantmelodymakam#7] opened 2016-12-14 11:06 UTC
When I run the extractor with a test audio file of 1 seconds, it fails: 
```
results = extractor.run(filename1)
  File "build/bdist.macosx-10.9-x86_64/egg/predominantmelodymakam/predominantmelodymakam.py", line 85, in run
  File "build/bdist.macosx-10.9-x86_64/egg/predominantmelodymakam/predominantmelodymakam.py", line 215, in select_contours
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

```
I figured out that if the audio is 2-seconds long, it works. So I suspect there is an issue with minimal pitch contour length in melodia.  
I would add a more informative error message.

**Comment by sertansenturk** [comment] 2016-12-14 11:18
Can you send me the audio file? Maybe there is a bug which persists indirectly on very short files.

**Comment by georgid** [comment] 2016-12-14 22:09
[vignesh_short.wav.zip](https://github.com/sertansenturk/predominantmelodymakam/files/653256/vignesh_short.wav.zip)

**Comment by sertansenturk** [comment] 2016-12-15 13:25
This seems to be an issue with the Essentia.PitchContours output. If the file is very short such that there is only a single contour, it returns an ndarray of ndarrays. If the track is sufficiently long, the method returns list of ndarrays. 

I tried to reproduce by taking the code out of predominantmelodymakam and isolating the error to report an issue in the Essentia repository, but I encountered some other errors, which I cannot figure out now. If you want, you can try to reproduce the issue and report. Otherwise, I'll look to this problem later in January, when I have more time.

**Comment by sertansenturk** [comment] 2017-02-05 20:51
Fixed by the commit https://github.com/sertansenturk/predominantmelodymakam/commit/36e3d34ecdde4c067e932706079b36bcb41fda08

**Closed as completed by sertansenturk** 2017-02-05 20:51 UTC
